name: Build (Linux + Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          g++ \
          libglfw3-dev \
          libfreetype-dev \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libswscale-dev \
          libx264-dev \
          libgl1-mesa-dev \
          pkg-config \
          rsync

    - name: Configure
      run: cmake -S . -B build -G Ninja

    - name: Build
      run: cmake --build build

  windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ninja + CMake
      uses: lukka/get-cmake@latest

    - name: Configure
      run: cmake -S . -B build -G Ninja

    - name: Build
      run: cmake --build build
