name: Build (Linux + Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          g++ \
          libglfw3-dev \
          libfreetype-dev \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libswscale-dev \
          libx264-dev \
          libgl1-mesa-dev \
          pkg-config \
          rsync

    - name: Configure
      run: cmake -S . -B build -G Ninja

    - name: Build
      run: cmake --build build

  windows:
    name: Build on Windows (MSYS2 MinGW)
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSYS2 with MinGW-w64
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja

    - name: Build using MinGW64 shell
      shell: msys2 {0}
      run: |
        mkdir -p build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
        ninja
